### PR TITLE
adding linter to the root directory of the repo

### PR DESCRIPTION
**Pull request by JelilFaisalAbudu**
- Adding linter to the root of the master branch as a requirement to check all lint errors in the code.

### CODE REVIEW

**Comment by JelilFaisalAbudu** [comment]
# Apple Clone Project Completed

My apple clone project is now completed and I am submitting it for your review and comments.
I follow the project requirements-background and gradient for building this project.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @JelilFaisalAbudu, you have done a great job with this project. 😄 Great use of HTML semantic

 👍 , However, before we can proceed we should improve on what we currently have. Kindly check the comments below to fix the changes:
* Let us improve the bottom => ```<aside class="aside-content">```. Since our main focus for this project is "using background and gradients", I strongly recommend you to replace the `````` with a ```<div>``` give them a unique class and use the background property on them
* Let us add a link to the "copyright" in the footer
* Let us fix the horizontal scroll

[OPTIONAL]
Let us add hover effect to the nav items

Kindly make these changes and submit ano0ther code review 🙂 
_Happy coding_ 👨‍💻 
Find me on slack @Daniel Larbi Addo

**Comment by JelilFaisalAbudu** [comment]
# Current Changes To The Project Per The TSE  Request

Following the request by the TSE of this project, all the required and the optional changes have been made.

These include:
[REQUIRED]
-using background images in the aside-content class instead of   elements.
- fixing the horizontal scroll.
-adding a link to the "copyright" in the footer. 

[OPTIONAL]
- adding a hover effect to the nav items.

**Comment by majovanilla** [comment]
Hi @JelilFaisalAbudu !

Good job with your project!! You included all the required changes and your page looks great! :medal_military: 

You are good to go! Congratulations!! :clap: 

**PROJECT APPROVED**

**Pull request merged**
